language: java
jdk:
- openjdk8
deploy:
  provider: heroku
  api_key:
    secure: cW+NOMnrDvma4OhtJbohArIiFbFQqz9EyiFqO63UX64n2PN5KMj+k+TLPutHY263faPOY1hYZw3WIOXSkDFpnQcOs/OYxEaUuuie4aKcALjk6uJnKhAOakDgh7UlZZ07MRwTYKa9QpKslCw5Jv+DOAX0b4Wsz5ZnT09zoJHaGFLy2Q87O/dnZ7gQJaeHyArzRlRHHnpeqcHLZ8eqsUiyvs9K1tnOn2MUrOWBgL84RbUvlZNXs7I0MC0B6DpTWWbMBXg9Op05b5gYpuxDdXiZNCkHHYLezVmGdTcVZpx2xKlEIh5PqXI1TDyTd66GXJ86OxiW//2zr212FIeWTx29rMdIIvvHw//ArGdoOG/O3mA2+ldij9MdEqlwFR8ByDtxNjaj5FBY78S8H2Va3zBtbDCRHjZ9z+903lXxnCJ12i/qz6X6hchFe7xcAjHmfV62KbVa66wDKLKGEbAznoATPR/27GsBuBcKrHGPcWzlQkFLZQZ8gn+2yw9o9O1pVdPxrzyeZTmwHaMFFszHZYD/lQx/3n6MG/P4KlVorFvtdV4kknehFKdBp01y0GZVvhBc/V8zeR6UdKm2D7KDsJDSiOiRkKYBdCGp++dN7zGcHeaDorNgRNc2VGUw4yk8iRfPCQH+u8WHcY5DjajE4WJJxRAnTUElxLbIZ4X4SzGh3AE=
  app: app-simple-notes
before_install:
- chmod +x mvnw